ALTER TYPE "TaskEventType" ADD VALUE IF NOT EXISTS 'MEMBER_ADDED';
ALTER TYPE "TaskEventType" ADD VALUE IF NOT EXISTS 'MEMBER_UPDATED';
ALTER TYPE "TaskEventType" ADD VALUE IF NOT EXISTS 'MEMBER_REMOVED';
ALTER TYPE "TaskEventType" ADD VALUE IF NOT EXISTS 'GROUP_CREATED';
ALTER TYPE "TaskEventType" ADD VALUE IF NOT EXISTS 'GROUP_UPDATED';
ALTER TYPE "TaskEventType" ADD VALUE IF NOT EXISTS 'GROUP_DELETED';
